build-AnalyticsHelperLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/analytics-helper"
	cp package.json "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/analytics-helper"
	cp index.mjs "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/analytics-helper"
	cd "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/analytics-helper" && npm install 