AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
Resources:
  S3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SAM-S3-Upload-Helper
      Description: This is a helper layer for handling s3 objects.
      ContentUri: ./s3-helper-layer/
      CompatibleRuntimes:
      - nodejs18.x
    Metadata:
      BuildArchitecture: x86_64
      BuildMethod: makefile
      SamResourceId: S3Layer
  AnalyticsHelperLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SAM-Analytics-Helpers
      Description: Analytics helper layer code.
      ContentUri: ./analytics-layer/
      CompatibleRuntimes:
      - nodejs18.x
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
      SamResourceId: AnalyticsHelperLayer