build-S3Layer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/s3-helper"
	cp package.json "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/s3-helper"
	cp index.mjs "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/s3-helper"
	cd "$(ARTIFACTS_DIR)/nodejs/node18/node_modules/s3-helper" && npm install 